"use client";
import { CssBaseline } from "@mui/material";
import { Provider } from "react-redux";
import CustomTheme from "../components/CustomTheme/CustomTheme";
import { store } from "../store";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <Provider store={store}>
        <CustomTheme>
          <CssBaseline />
          <body>{children}</body>
        </CustomTheme>
      </Provider>
    </html>
  );
}
