"use client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import {
  Box,
  BoxProps,
  CssBaseline,
  styled,
  useMediaQuery,
  useTheme,
} from "@mui/material";
import { CustomTheme } from "components/CustomTheme";
import { Header } from "components/Header";
import { MenuDesktop } from "components/Menu/Desktop/MenuDesktop";
import { Provider } from "react-redux";
import { store } from "store";
import { useState } from "react";

const ContentWrapper = styled(Box)<BoxProps>(({ theme }) => ({
  display: theme.breakpoints.up("md") ? "flex" : "block",
}));

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [queryClient] = useState(() => new QueryClient());
  const theme = useTheme();
  const matches = useMediaQuery(theme.breakpoints.up("md"));
  return (
    <html>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <QueryClientProvider client={queryClient}>
        <Provider store={store}>
          <CustomTheme>
            <CssBaseline />
            <body>
              <ContentWrapper>
                {matches && <MenuDesktop />}
                <Box
                  sx={{
                    width: "100%",
                  }}
                >
                  <Header />
                  <main>{children}</main>
                </Box>
              </ContentWrapper>
            </body>
            <ReactQueryDevtools initialIsOpen={false} />
          </CustomTheme>
        </Provider>
      </QueryClientProvider>
    </html>
  );
}
