"use client";
import { CssBaseline } from "@mui/material";
import { Provider } from "react-redux";
import CustomTheme from "../components/CustomTheme/CustomTheme";
import Header from "../components/Header/Header";
import { store } from "../store";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <Provider store={store}>
        <CustomTheme>
          <CssBaseline />
          <body>
            <Header />
            <main>{children}</main>
          </body>
        </CustomTheme>
      </Provider>
    </html>
  );
}
